on:
  workflow_dispatch:
    inputs:
      target:
        description: 'Release Branch (e.g., testing). Defaults to branch name.'

permissions:
  contents: write

name: Generate Release
jobs:
  generate-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout last 500 commits (for <commits> to work)
        uses: actions/checkout@v4
        with:
          fetch-depth: 500

      - name: Get target
        run: |
          echo "TARGET=${{ github.event.inputs.target || github.ref }}" > $GITHUB_ENV
      
      - name: Generate Release Text
        run: |
          python3 ./.github/workflows/changelog.py "${{ env.TARGET }}" ./output.env ./changelog.md --workdir .
          source ./output.env
          echo "TITLE=${{ TITLE }}" >> $GITHUB_ENV
          echo "TAG=${{ TAG }}" >> $GITHUB_ENV

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ env.TITLE }}
          tag: ${{ env.TAG }}
          body_path: ./changelog.md
          make_latest: ${{ env.TARGET == 'stable' }}
          prerelease: ${{ env.TARGET != 'stable' }}